name: pr-actions
on:
  pull_request:
    branches:
      - 'main'
jobs:
  Run-Playwright-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install-dependencies
      - run: playwright install --with-deps
      - run: make run-headless
        env:
          FORM_AUTHENTICATION_USERNAME: ${{ secrets.FORM_AUTHENTICATION_USERNAME }}
          FORM_AUTHENTICATION_PASSWORD: ${{ secrets.FORM_AUTHENTICATION_PASSWORD }}
